/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Ignore;
import org.junit.Test;

/**
 * Generated sample test from Gradle init.
 *
 * Disabled because this project uses com.iam.common.* classes, and the
 * generated org.example.Library class is not part of this repository.
 */
@Ignore("Generated sample test not applicable to this project")
public class LibraryTest {
	@Test
	public void disabled() {
		// no-op
	}
}
