-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;
create schema if not exists IAM;
CREATE TABLE IF NOT EXISTS IAM.identities
(
    id uuid,
    name character varying(255) NOT NULL,
    secret bytea NOT NULL,
    salt bytea NOT NULL,
    created_time timestamp with time zone,
    updated_time timestamp with time zone,
    type character varying(20),
    status character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS IAM.users
(
    firstname character varying(255),
    lastname character varying(255),
    country character varying,
    timezone character varying,
    id uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS IAM.applications
(
    id uuid,
    name character varying,
    created_by uuid,
    created_time timestamp with time zone,
    updated_time timestamp with time zone,
    permission_index bigint DEFAULT 1,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS IAM.sessions
(
    session_id character varying[] NOT NULL,
    user_id uuid NOT NULL,
    created_time timestamp with time zone NOT NULL,
    ttl bigint NOT NULL,
    PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS IAM.perrmissions
(
    application_id uuid NOT NULL,
    id uuid NOT NULL,
    scope character varying COLLATE pg_catalog."default" NOT NULL,
    enum_index bigint NOT NULL,
    CONSTRAINT perrmissions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS IAM.users
    ADD FOREIGN KEY (id)
    REFERENCES IAM.identities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS IAM.applications
    ADD FOREIGN KEY (created_by)
    REFERENCES IAM.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS IAM.applications
    ADD FOREIGN KEY (id)
    REFERENCES IAM.identities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS IAM.sessions
    ADD FOREIGN KEY (user_id)
    REFERENCES IAM.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS IAM.perrmissions
    ADD FOREIGN KEY (application_id)
    REFERENCES IAM.applications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
END;