/*
 * This source file was generated by the Gradle 'init' task
 */
package com.iam.common;

/**
 * Placeholder for shared OAuth-related utilities/types.
 *
 * This is a reference implementation; extend this class with shared logic
 * as the IAM project evolves.
 */
public class OAuth {

	public OAuth() {
		// no-op
	}
}
